### ISSUE TITLE
What's the verdict?

### ISSUE THREAD

**Issue by mizzao** [rajanand02/Meteor-svg#1]
How good are reactive SVGs that you've tried out?

**Comment by rajanand02** [comment]
It was performing well but svg's are quite complicated to design and maintain so we decided to minimise the use in our production application.

**Comment by mizzao** [comment]
I've found that using d3 with Meteor requires a hybrid programming approach that uses Meteor to generate the DOM and d3 to transform/translate and animate it, and it's a lot easier than just using one of the paradigms by itself. You could consider trying that for your SVG implementation.
